RANCHER-1657: point to image repos on Docker Hub
folio-org/folio-helm-v2 pull request #140
Opened 2024-08-27 14:44 UTC by yaroslavishchenko

Related Jira Ticket:
[RANCHER-1657: Eureka. Switch from Kitfox ECR images to the DockerHub images in *-keycloak modules in the folio-helm-v2 charts](https://folio-org.atlassian.net/browse/RANCHER-1657)

2024-08-27 14:58 UTC, sergii-msn approved these changes

2024-08-27 15:10 UTC, aatoyan approved these changes

2024-08-28 14:04 UTC, epam-avramenko requested changes

2024-08-28 14:20 UTC, yaroslavishchenko commented on charts/mod-consortia-keycloak/values.yaml
> +  repository: folioci/mod-consortia-keycloak
@epam-avramenko
Fixed accordingly to your request.
Thanks.

2024-08-29 13:53 UTC, epam-avramenko approved these changes

2024-08-29 13:58 UTC, eldiiar-duishenaliev approved these changes

2024-08-29 18:13 UTC, merged