RANCHER-1122 add new module
folio-org/folio-helm-v2 pull request #65
Opened 2023-12-01 13:16 UTC by aatoyan

Adding new module [mod-marc-migrations](https://github.com/folio-org/mod-marc-migrations)

2023-12-01 13:23 UTC, eldiiar-duishenaliev requested changes
Main chart version should be increased by +1 as well

2023-12-01 13:23 UTC, eldiiar-duishenaliev commented on charts/mod-marc-migrations/values.yaml
> +  repository: folioci/mod-search
incorrect registry path

2023-12-04 09:47 UTC, aatoyan commented on charts/mod-marc-migrations/values.yaml
> +javaOptions: -XX:MaxRAMPercentage=85.0 -XX:+UseG1GC
DIscussed with developer

2023-12-04 10:45 UTC, eldiiar-duishenaliev approved these changes

2023-12-06 11:51 UTC, merged